-- runs automatically on first container start
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER MATRIX_USER IDENTIFIED BY "Neo2025"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO MATRIX_USER;
GRANT CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO MATRIX_USER;
